### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by liaohuanquan** [Temperature6/EasyVFDClock#1]
可以把立创的工程文件也上传一下吗谢谢！，你做的这个项目真的很棒

**Comment by Temperature6** [comment]
立创工程在 Hardware/VFD_Clock 下面

**Comment by liaohuanquan** [comment]
方便透露一下你购买的元器件大概用了多少钱吗？

**Comment by Temperature6** [comment]
最贵的是VFD屏幕，38r，单片机五六块，CH340C一块左右，AT24C02 5毛吧，RTC电池2块，高精度晶振1.5r 5个，电阻电容没法计，50基本上能搞定

**Comment by liaohuanquan** [comment]
不打算设计一个外壳吗，我觉得有一个透明外壳很酷

**Comment by Temperature6** [comment]
不太会建模（悲）

**Comment by liaohuanquan** [comment]
我想添加你的联系方式有一些问题，方便添加一下吗
